on:
  workflow_dispatch:
name: 🚀 Deploy website on Click
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Deploy from test branch
      - name: 📂 Sync files (Test)
        if: github.ref == 'refs/heads/test'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 15.204.197.218
          username: ${{ secrets.TEST_FTP_USERNAME }}
          password: ${{ secrets.TEST_FTP_PASSWORD }}
          protocol: ftp
          server-dir: /

      # Deploy from main branch
      - name: 📂 Sync files (Main)
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 15.204.197.218
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /